### ISSUE TITLE
Rename GPIO pin from Armbian OS 23.02.1 for Odroid C2 ?

### ISSUE THREAD

**Issue by mikebzh44** [armbian/os#11]
Hi.

I'm using my Odroid C2 to run Klipper / Moonraker / Mainsail and to drive my 3D printer.

Now I want to drive a relay board using GPIO so I can power on and off my printer.

This feature is embeded in Moonraker but I have to use the GPIO pin name.

When I look on my Odroid C2 : 

$ gpioinfo gpiochip1|grep J2
        line  78: "J2 Header Pin35" unused input active-high
        line  82: "J2 Header Pin36" unused input active-high
        line  83: "J2 Header Pin31" unused input active-high
        line  88: "J2 Header Pin32" unused input active-high
        line  89: "J2 Header Pin26" unused input active-high
        line  92: "J2 Header Pin29" unused input active-high
        line  93: "J2 Header Pin24" unused input active-high
        line  94: "J2 Header Pin23" unused input active-high
        line  95: "J2 Header Pin22" unused input active-high
        line  96: "J2 Header Pin21" unused input active-high
        line  97: "J2 Header Pin18" unused input active-high
        line  98: "J2 Header Pin33" unused input active-high
        line  99: "J2 Header Pin19" unused input active-high
        line 100: "J2 Header Pin16" unused input active-high
        line 101: "J2 Header Pin15" unused input active-high
        line 102: "J2 Header Pin12" unused input active-high
        line 103: "J2 Header Pin13" unused input active-high
        line 104: "J2 Header Pin8" unused input active-high
        line 105: "J2 Header Pin10" unused input active-high
        line 111: "J2 Header Pin11" unused input active-high
        line 113: "J2 Header Pin7" unused input active-high

Pin's name use blank.

Meanwhile, the same command on a Raspberry Pi 3 : 

$ gpioinfo gpiochip0
gpiochip0 - 54 lines:
        line   0:     "ID_SDA"       unused   input  active-high
        line   1:     "ID_SCL"       unused   input  active-high
        line   2:       "SDA1"       unused   input  active-high
        line   3:       "SCL1"       unused   input  active-high
        line   4:  "GPIO_GCLK"       unused  output  active-high
        line   5:      "GPIO5"       unused   input  active-high
        line   6:      "GPIO6"       unused   input  active-high
        line   7:  "SPI_CE1_N"       unused   input  active-high
        line   8:  "SPI_CE0_N"       unused   input  active-high
        line   9:   "SPI_MISO"       unused   input  active-high
        line  10:   "SPI_MOSI"       unused   input  active-high
        line  11:   "SPI_SCLK"       unused   input  active-high
        line  12:     "GPIO12"       unused   input  active-high
        line  13:     "GPIO13"       unused   input  active-high
        line  14:       "TXD1"       unused   input  active-high
        line  15:       "RXD1"       unused   input  active-high
        line  16:     "GPIO16"       unused   input  active-high
        line  17:     "GPIO17"  "moonraker"  output  active-high [used]
        line  18:     "GPIO18"       unused   input  active-high
        line  19:     "GPIO19"       unused   input  active-high
        line  20:     "GPIO20"       unused   input  active-high
        line  21:     "GPIO21"       unused   input  active-high
        line  22:     "GPIO22"       unused   input  active-high
        line  23:     "GPIO23"       unused   input  active-high
        line  24:     "GPIO24"       unused   input  active-high
        line  25:     "GPIO25"       unused   input  active-high
        line  26:     "GPIO26"       unused   input  active-high
        line  27:     "GPIO27"       unused   input  active-high
        line  28:         "NC"       unused   input  active-high
        line  29: "LAN_RUN_BOOT" unused input active-high
        line  30:       "CTS0"       unused   input  active-high
        line  31:       "RTS0"       unused   input  active-high
        line  32:       "TXD0"       unused   input  active-high
        line  33:       "RXD0"       unused   input  active-high
        line  34:    "SD1_CLK"       unused   input  active-high
        line  35:    "SD1_CMD"       unused   input  active-high
        line  36:  "SD1_DATA0"       unused   input  active-high
        line  37:  "SD1_DATA1"       unused   input  active-high
        line  38:  "SD1_DATA2"       unused   input  active-high
        line  39:  "SD1_DATA3"       unused   input  active-high
        line  40:   "PWM0_OUT"       unused   input  active-high
        line  41:   "PWM1_OUT"       unused   input  active-high
        line  42:    "ETH_CLK"       unused   input  active-high
        line  43:   "WIFI_CLK"       unused   input  active-high
        line  44:       "SDA0"       unused   input  active-high
        line  45:       "SCL0"       unused   input  active-high
        line  46:   "SMPS_SCL"       unused   input  active-high
        line  47:   "SMPS_SDA"       unused  output  active-high
        line  48:   "SD_CLK_R"       unused   input  active-high
        line  49:   "SD_CMD_R"       unused   input  active-high
        line  50: "SD_DATA0_R"       unused   input  active-high
        line  51: "SD_DATA1_R"       unused   input  active-high
        line  52: "SD_DATA2_R"       unused   input  active-high
        line  53: "SD_DATA3_R"       unused   input  active-high

In moonraker configuration file, I have to use GPIO17 to trigger the state.

But on my Odroid C2, I can't because Moonraker can't parse GPIO name.

Is it possible to rename the GPIO from "J2 Header Pin7" to "J2_Header_Pin7" for example ? Withour recompiling th OS, of course :D 

Thanks

**Comment by igorpecovnik** [comment]
Hardware related support: https://forum.armbian.com/forum/109-odroid-c2/
