### ISSUE TITLE
aml-s9xx-box

### ISSUE THREAD

**Issue by bearklake** [armbian/os#142]
### Which board images would you like us to rebuilt?

Please can you make rolling release for aml-s9xx-box with EDGE kernel?

**Comment by igorpecovnik** [comment]
FYI. We are anyway planning to switch CURRENT kernel to 6.6.y on all families. First one was [merged today](https://github.com/armbian/build/pull/6079), others depends on time / maintainers availability / users help. 

https://armbian.atlassian.net/browse/AR-2005
In most cases, its only [this](https://github.com/armbian/build/commit/61b23605f93034fa15cd0b784ad0a29ca3ef39f7).

**Comment by igorpecovnik** [comment]
Closing. We are providing them both for some time now.
