### ISSUE TITLE
add board aml-s9xx-box

### ISSUE THREAD

**Issue by esaaprillia** [armbian/os#168]
### Which board images would you like us to rebuilt?

hy @igorpecovnik 

what do I have to do? I want to build an aml-s9xx-box
![Screenshot_2024-02-18_073823](https://github.com/armbian/os/assets/122262432/f15f192d-8f92-41cd-98e1-f088fbc1b326)

**Comment by esaaprillia** [comment]
can you add dtb for amlogic-s905x meson-gxl-s905x-p212.dtb i want to try on my tv box

**Comment by igorpecovnik** [comment]
This repository issues provides two types of services:

- Armbian Linux Software Package Import Request
- Armbian OS Image rebuild request

> can you add dtb for amlogic-s905x meson-gxl-s905x-p212.dtb i want to try on my tv box

We are not doing that. Support for tv boxes is provided by community:
https://forum.armbian.com/forum/24-tv-boxes/
There you can look for people that could be making dtb for your tv box.
