### ISSUE TITLE
OrangePi 5 images issues

### ISSUE THREAD

**Issue by drozdi70** [armbian/os#198]
### Which board images would you like us to rebuilt?

Please remake orangepi 5 plus images, all of them are not bootable.
all edge 6.8. kernel :(
Even myself I tried to use for armbian repository and build my own image of armbian and it is not bootable also :(

**Comment by drozdi70** [comment]
all bookworm the same, even I tried trixie and the result is the same :(
images writen from xz for img with Ethcher, USBImagier Rasperry Pi Imager different cards...
when I took Debian and write to the card (kernel 6.1) all is fine

**Comment by igorpecovnik** [comment]
![image](https://github.com/armbian/os/assets/6281704/1cebf829-7775-43dc-acb4-48015735a656)

"Reporting bugs" -> https://www.armbian.com/bugs/

**Comment by igorpecovnik** [comment]
> all edge 6.8. kernel :(

Use Armbian with kernel 6.1 and it will work. For 6.8.y you need to read / use forums for support.

**Comment by igorpecovnik** [comment]
Added this to download pages: **Kernel 6.8.y is at experimental support level. Not all features work but it runs fairy stable**

**Comment by drozdi70** [comment]
what are you doing?please dont cheat here !!!!Temat: Re: [armbian/os] OrangePi 5 images issues (Issue #198)Data: 2024-05-27 19:36Nadawca: "Igor" ***@***.***&gt;Adresat: "armbian/os" ***@***.***&gt;; DW: "DroZDi" ***@***.***&gt;; "Author" ***@***.***&gt;; 

Added this to download pages: Kernel 6.8.y is at experimental support level. Not all features work but it runs fairy stable

**Comment by igorpecovnik** [comment]
> what are you doing?

Adding missing information. Otherwise, what you are asking has been already answered: https://forum.armbian.com/forum/64-standard-support/ 

When your board doesn't start, you go here:
https://forum.armbian.com/forum/31-sd-card-and-psu-issues/

Community provides you support. Or not.
