### ISSUE TITLE
Rockchip rk3066 support

### ISSUE THREAD

**Issue by actraiser30** [armbian/os#211]
### Which board images would you like us to rebuilt?

Hello I did not know we're to post this 

Is it possible to make an image for Rockchip rk3066 arm boards like the Marsboard and the mk808b ??

There is Linux support from what is see

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/arm/boot/dts/rockchip

Thanks

**Comment by igorpecovnik** [comment]
> Hello I did not know we're to post this

Perhaps here https://forum.armbian.com/forum/22-new-boards/ would be better?

Here we only accept requests to enable / disable different configurations that you / someone has reported as working. https://github.com/armbian/os/wiki/Enable-build-configuration for boards that are already in the system. Adding a new board can be a time consuming job, requires personal and requires hardware as untested things is pointless dealing with. This part is on you: https://docs.armbian.com/Developer-Guide_Adding-Board-Family/

After board config is reviewed and accepted (this is almost full time job for one person) to the build framework https://github.com/armbian/build/pulls images are added automatically to [community build stream](https://github.com/armbian/community), which re-generates all images once per week. For higher support standard, board needs to have a maintainer and someone needs to take care of his bills while working for you. We don't need nor can afford to support all hardware. We provide tooling that this becomes manageable without extreme hard work. Use tools https://github.com/armbian/build

> There is Linux support from what is see

Sadly this means nothing. We have quite a big team doing 24/7 to enable and keep those "supported" board supported. [This](https://docs.armbian.com/Release_Changelog/#v2451-2025-25-5) is 3 months of work on top of what supposed to work.

**Comment by actraiser30** [comment]
Hi, thanks for the heads up 

It was worth asking,looks very complicated the procedure,maybe in the future could be possible somehow.the mk808b is a decent arm board and it would be great to have at least a cli only os debian bookworm or bullseye for example

Thanks again

**Comment by igorpecovnik** [comment]
> looks very complicated the procedure

Without our tools, things would only be a lot more complex ;)

Yes, dealing with this can be hard, but if not else, time consuming, also for experienced people. Every device behaves differently and brings different problems. Once board is brought to the Armbian level, so you can have some simple Debian experience, any other distribution can take it from here with absolutely zero additional work. We invest weeks to do something for you and you are not happy as you expect its done in no time, and someone else, that takes our work and invest nothing, makes you happy as they deliver you image in no time ... And making someone happy is all that is exchanged here.

**Comment by actraiser30** [comment]
No problem 

If I give you an old image made for this board years ago,ubuntu 12 or 13 I think would it make things easier to take the necessary files from it for an Armbian image??

Thanks

**Comment by igorpecovnik** [comment]
> If I give you an old image made for this board years ago,ubuntu 12 or 13 I think

https://docs.armbian.com/#what-is-armbian

Once Armbian is on, you can make Ubuntu from it in zero time. This is what our copycats do. Some old hacked together unofficial images (Ubuntu never supported any of this hardware) are of little use for software development. 

The key in Armbian support is that all images can be rebuild at any moment. Once you are in, you always gets latest Ubuntu or Debian user space applications. Which are relevant for users.

**Comment by omarkhali** [comment]
out of the subject

How do I add this command? sed -i -e "5 s/$/ systemd.unified_cgroup_hierarchy=0/" /boot/extlinux/extlinux.conf to ha.sh

When I add this command myself, the process fails

thank you In advance

@igorpecovnik
