### ISSUE TITLE
Please start a build for mba8mpxl-ras314 and mba8mpxl for 6.11 kernel

### ISSUE THREAD

**Issue by tq-schmiedel** [armbian/os#261]
### Which board images would you like us to rebuilt?

After Kernel update, can you please build mba8mpxl-ras314 and mba8mpxl boards for testing.

I think these images could be a good starting point for the Website.

**Comment by igorpecovnik** [comment]
Accept invite, then proceed this way:
https://docs.armbian.com/Process_CI/

**Comment by tq-schmiedel** [comment]
All clear. The build went through cleanly, and I have downloaded the relevant images (from my incoming) and will now test them.

Assuming there should be no problems, how can I copy them to /dl folder?

Thanks for the support.

**Comment by igorpecovnik** [comment]
> Assuming there should be no problems, how can I copy them to /dl folder?

As this starts mirror and torrent synchronisation, this part is done by us once you confirm images are ready. This eats bandwidth for nothing in case we need to re-do images. If they are ready, I am moving them. Index is generated automatically once they are there.

**Comment by igorpecovnik** [comment]
Oh, since kernel was changed and since we already have 24.8.4 at the download position, version bump is required. Run rebuild once again tacking "bump version".

**Comment by igorpecovnik** [comment]
P.S. Normally we would just overwrite those files, but torrent network have issues with that.

**Comment by tq-schmiedel** [comment]
OK, I found a few bugs anyway, Desktop won't start and a KERNEL option is missing.

I would add my changes to armbian/build and then start the build with "bump version" if that's ok.

**Comment by igorpecovnik** [comment]
> I would add my changes to armbian/build and then start the build with "bump version" if that's ok.

Yes, after merge ofc.
