### ISSUE TITLE
Image für Kobol helios64

### ISSUE THREAD

**Issue by Suk-RAM** [armbian/os#49]
### Which software package would you like that is mirrored?

Dear reader, 

On https://wiki.kobol.io/download/ one can find a link that points to https://dl.armbian.com/helios64/archive/Armbian_21.05.1_Helios64_buster_current_5.10.35.img.xz . But this destination is no longer availabel. 

I read on https://www.armbian.com/helios64/ that there is a maintainer missing. I would expect this is the reason why the os-image is not available anymore. Are there any older images available for download or is it likely that you find a new maintainer pretty soon?

Regards

Suk-RAM

**Comment by igorpecovnik** [comment]
Non supported boards are hooked to automated build system but if they don't build, they are eventually removed as we can't afford to fix them. I think this was the case with Helios64.

>Are there any older images available for download

https://archive.armbian.com

Keep in mind that this hardware support was never finished. In case of other questions, better try here https://forum.armbian.com/tags/helios64/
